title: Tech Logs
name: "Monir's Notes"
author: Monir Ahmed Tanveen
linkedin_username: monirahmedtanveen
twitter_username: monirtanveen
baseurl: "/tech.logs"
description: Document my learning notes.
profile_url: "https://monirahmedtanveen.github.io/"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
